import Logger from "/src/t13ne/core/Logger.js";
import { EventBus } from "/src/t13ne/core/EventBus.js";
import { T13Plot } from "../narrative/t13ne-plots.js";

/**
 * T13StoryMode
 * The "Auto-Pilot" mode for the T13 Narrative Engine.
 * It manages the lifecycle of a Story Demon (Story-rank Plot),
 * ensuring it is properly cascaded (spread) and processed by the Referee.
 */
class T13StoryMode {
    constructor() {
        this.isActive = false;
        this.t13ne = null;
        this.activeStory = null;
    }

    initialize(t13ne) {
        this.t13ne = t13ne;
        Logger.message("T13StoryMode: Initialized.");
    }

    /**
     * Toggles Story Mode.
     * When active, the Referee heartbeat will drive the narrative using AI.
     */
    async toggle(state) {
        this.isActive = state !== undefined ? state : !this.isActive;
        Logger.message(`T13StoryMode: Story Mode is now ${this.isActive ? 'ACTIVE' : 'INACTIVE'}.`);

        if (this.isActive) {
            await this.ensureStoryDemon();
            this.startEngineHeartbeat();
            EventBus.emit('storymode:started');
        } else {
            this.stopEngineHeartbeat();
            EventBus.emit('storymode:stopped');
        }
    }

    /**
     * Ensures a Story Demon is active and has its initial spread.
     */
    async ensureStoryDemon() {
        const Plots = this.t13ne.getModule('Plots');
        const Referee = this.t13ne.getModule('Referee');

        // 1. Find or Create Story Demon
        this.activeStory = Plots.plots.find(p => p.Rank === 'Story' && p.isActive && !p.isResolved);

        if (!this.activeStory) {
            Logger.message("T13StoryMode: Summoning new Story Demon...");

            // Create a Story Plot with a random conflict context
            this.activeStory = new T13Plot({
                Name: "The Automated Tapestry",
                Rank: "Story",
                Description: "An AI-driven story exploring the depths of the T13 Narrative Engine.",
                genre: "T13 Core",
                era: "Timeless",
                TensionLevel: 2 // Start at Low Tension
            }, this.t13ne);

            // 2. "And Spread" - Cascade the plot using the Story Spread (3-Act structure)
            // This populates the sub-plots with Acts and Scenes based on card spreads.
            await this.activeStory.cascadePlot({
                startRank: 'Story',
                recursive: true
            });

            // 3. Register with Plots module
            if (!Plots.plots.includes(this.activeStory)) {
                Plots.plots.push(this.activeStory);
            }

            Logger.message(`T13StoryMode: Story Demon "${this.activeStory.Name}" summoned and spread.`);
        }

        // 4. Ensure Drama and Tension are tracking
        const Drama = this.t13ne.getModule('Drama');
        if (Drama) {
            Drama.setTensionLevel(this.activeStory.tensionLevel);
        }
    }

    startEngineHeartbeat() {
        const Referee = this.t13ne.getModule('Referee');
        if (Referee) {
            // Accelerate heartbeat for Story Mode demo visibility (every 10s)
            Referee.startHeartbeat(10000);
            Logger.message("T13StoryMode: Referee heartbeat started.");
        }
    }

    stopEngineHeartbeat() {
        const Referee = this.t13ne.getModule('Referee');
        if (Referee) {
            Referee.stopHeartbeat();
            Logger.message("T13StoryMode: Referee heartbeat stopped.");
        }
    }

    /**
     * The Story Mode UI in the companion app listens for 'chronicle:entry'
     * to show the narrative flow generated by the Referee and the Story plots.
     */
}

export default new T13StoryMode();
